name: Build Action
description: Builds typst documents
inputs:
  document:
    description: "Path to .typ file"
    required: true
  name:
    description: "Name of the pdf document"
    required: true
  typst_version:
    description: Typst version
    required: false
    default: "v0.8.0"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: build.sh ${{ inputs.document }} ${{ inputs.name }}
      name: Build document
      shell: bash
      env:
        TYP_VERSION: ${{ inputs.typst_version }}
    - uses: actions/upload-artifact@v3.1.3
      name: Upload PDF
      with:
        name: "${{ inputs.name }}"
        path: "${{ inputs.name }}"
